### ISSUE TITLE
add some missing commands?

### ISSUE THREAD

**Issue by mathjiajia** [latex-lsp/tree-sitter-latex#36]
It seems that the commands below are not included:
```latex
\newtheorem*{}{}
\numberwithin{}{}
\DeclarePairedDelimiter{}{}{}
\DeclarePairedDelimiterX{}[]{}{}{}
\title[]{}
\author{}
```

Also, the `abstract` environment is not included.
```latex
\begin{abstract}
\end{abstract}
```

**Comment by pfoerster** [comment]
Thanks for the report! I have added the starred variants of the commands to define theorem environments and
there is a new rule that is used to parse paired delimiters (`\DeclarePairedDelimiter` and `DeclarePairedDelimiterX`). 

Regarding the other commands, I am unsure on how to proceed. I do no think that these commands and the `abstract` environment require special syntax so the `generic_command` and `generic_environment` rules should already parse those cases correctly. In the long term, we cannot add a rule for every possible command because this approach does not scale well (the generated parser would become even larger).

**Comment by clason** [comment]
> Regarding the other commands, I am unsure on how to proceed. I do no think that these commands and the abstract environment require special syntax so the generic_command and generic_environment rules should already parse those cases correctly. In the long term, we cannot add a rule for every possible command because this approach does not scale well (the generated parser would become even larger).

In general, I agree, although the `\title` command does feel special to me -- I see it as of the same class as, e.g., `\chapter` (i.e., the top-most level of the contents hierarchy).

(`\author` is more arguable; VimTeX gives it a separate highlight (which I map to the same color as `\title`), which I kinda like.)

**Comment by pfoerster** [comment]
> `\author` is more arguable

Actually, I think `\author` makes sense because you have to use the `\and` command to separate the names. I have added a new rule. Besides, there is now a rule which handles the `\title` command 👍 .

**Comment by clason** [comment]
Great, will update the Neovim queries today or tomorrow!

**Comment by pfoerster** [comment]
> Also, the abstract environment is not included.

@clason What do you think about the `abstract` environment? I think we have to include `document` as well if we add it.

**Comment by clason** [comment]
I agree; if you include one, you should include the other. But I'm not quite sold on how `abstract` should be special over, say, `theorem` or any other general environment.

**Comment by clason** [comment]
There's a better case for `document` -- but only if it makes a difference for parsing (say, detecting stuff that should only be in the preamble, like `@`).

**Comment by pfoerster** [comment]
> I agree; if you include one, you should include the other. But I'm not quite sold on how abstract should be special over, say, proof or any other general environment.

I think this might also complicate the queries by making them even more dependent on the grammar. Let's say I add the `document` and `abstract` environment to the grammar. Then, the queries also need to be updated because keeping the same queries breaks the highlighting of these environments. Without these extra rules, one can easily add another query using predicates similar to how the math environments are handled.

> There's a better case for document -- but only if it makes a difference for parsing (say, detecting stuff that should only be in the preamble, like @).

I think you could disallow `\usepackage` and `\documentclass` by requiring them inside a `preamble` node that can only appear at the top-level but I am not sure if this could break some valid use cases.

**Comment by clason** [comment]
> I think this might also complicate the queries by making them even more dependent on the grammar. Let's say I add the document and abstract environment to the grammar. Then, the queries also need to be updated because keeping the same queries breaks the highlighting of these environments. Without these extra rules, one can easily add another query using predicates similar to how the math environments are handled.

Yeah, I don't see much advantage for this, either. (If anything, it's an argument that _math_ environments should be separate, as a) these make a huge difference for the contents and b) it may be easier/more performant to keep the list of all math environments in the parser rather than the query.)

In general, I wouldn't much worry about breaking queries, as a) nvim-treesitter is still declared as experimental, so people get what they deserve and b) I try to be pretty quick about adapting to parser changes. But the change should have some tangible benefit, of course; otherwise it's just churn for no gain.

**Comment by pfoerster** [comment]
> If anything, it's an argument that math environments should be separate, as a) these make a huge difference for the contents and b) it may be easier/more performant to keep the list of all math environments in the parser rather than the query

Yeah, that makes sense 👍 . I have added a new `math_environment` rule. This should make the queries much simpler because you won't need to copy the list of math environments four times.

**Comment by clason** [comment]
> there is a new rule that is used to parse paired delimiters (\DeclarePairedDelimiter and DeclarePairedDelimiterX).

Hmmm, that doesn't seem to be quite working for me: for 
```latex
\DeclarePairedDelimiter{foo}{(}{)}
```
(note that this command doesn't take an optional argument) I get
```
ERROR [0, 0] - [0, 34]
  "\DeclarePairedDelimiter" [0, 0] - [0, 23]
  "{" [0, 23] - [0, 24]
  word [0, 24] - [0, 27]
  "}" [0, 27] - [0, 28]
  "{" [0, 28] - [0, 29]
  "(" [0, 29] - [0, 30]
  "}" [0, 30] - [0, 31]
  "{" [0, 31] - [0, 32]
  ")" [0, 32] - [0, 33]
  "}" [0, 33] - [0, 34]
```

**Comment by mathjiajia** [comment]
Thanks for the update.

@clason I think you should add `\` before `foo`.
Even thought, there is still an error with `\DeclarePairedDelimiter{\foo}{(}{)}`:
```
paired_delimiter_definition [120, 0] - [120, 35]
  declaration: curly_group_command_name [120, 23] - [120, 29]
    command: command_name [120, 24] - [120, 28]
  left: curly_group_impl [120, 29] - [120, 32]
    ERROR [120, 30] - [120, 31]
  right: curly_group_impl [120, 32] - [120, 35]
    ERROR [120, 33] - [120, 34]
```

It seems that the current parser of `\DeclarePairedDelimiter` only accept `\ lparen` and `rparen` (start with `\`) as its second and third parameters.
(Note that `\DeclarePairedDelimiter{\foo}{(}{)}` will not cause any error with the compiling, e.g., `\(\foo{a}\)` gives `(a)` correctly.)

**Comment by clason** [comment]
> @clason I think you should add \ before foo.

You are right, of course 🤦  (In my defense, it was quite late already after I had taken care of all the other updates ;))

**Comment by pfoerster** [comment]
> Even thought, there is still an error with \DeclarePairedDelimiter{\foo}{(}{)}:

Thanks. This should be fixed now. There was an error with the `curly_group_impl` rule.
