### ISSUE TITLE
Syntax highlight for `align` environments

### ISSUE THREAD

**Issue by kylechui** [latex-lsp/tree-sitter-latex#4]
I'm using tree-sitter with the latest Neovim nightly, and have run into the issue where text inside an `align` environment (between `\begin{align*}` and `\end{align*}` is not treated as math text. Here's a screenshot of some regular math text:
![image](https://user-images.githubusercontent.com/48545987/120564181-e6b7a480-c3f9-11eb-820a-71a9ebcc3bf0.png)
Here's a screenshot of math inside an `align` environment:
![image](https://user-images.githubusercontent.com/48545987/120564336-30a08a80-c3fa-11eb-83d7-98ccf9306ad6.png)
It doesn't show up in the screenshot, but the math inside the `align` environment occasionally switches to the default red because it doesn't have the highlight group attached. Thanks for your work on the project and let me know if there's anything else I need to add to this issue, or if this is the wrong place to put it!

**Comment by pfoerster** [comment]
Thanks for the report. Possibly this issue is placed inside the wrong repository. This repository was originally intended to replace the parser of `texlab` but in the end I did not end up replacing it so this grammar was reused to provide some benefit for the Neovim community. Note that this repository does not provide any highlighting queries. Instead, this grammar only provides the actual parser. So I think you are better up reporting this at `nvim-treesitter` as I am not in charge of the highlighting queries. From the parsing side, there should be no problem with distinguishing math environments. If there is, please feel free to open another issue, add a comment here or send me a PR.

**Comment by kylechui** [comment]
Ah I see now, I'll raise an issue in the `nvim-treesitter` repository. Sorry about that!
