### ISSUE TITLE
Feature request: parity with regex-based vim-tex-syntax highlighter

### ISSUE THREAD

**Issue by ahelwer** [latex-lsp/tree-sitter-latex#6]
I was experimenting with using this grammar in neovim through the [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) plugin. Unfortunately the highlighting this grammar provides does not compare favorably with neovim's [built-in regex-based latex highlighter](https://github.com/vim/vim/blob/master/runtime/syntax/tex.vim). Here is an example from a tikz file of mine (file available [here](https://gitlab.com/ahelwer/ahelwer.gitlab.io/-/blob/master/scratch/probabilistic-distsys/knuth-yao.tex)); the first is regex-based, the second is tree-sitter based:
<img src="https://user-images.githubusercontent.com/718765/124298274-11486a80-db2a-11eb-8a9f-dded05894a4b.png" width=45% height=45%>         <img src="https://user-images.githubusercontent.com/718765/124298374-2de4a280-db2a-11eb-9b8e-934e4bce510e.png" width=45% height=45%>
My chosen colorscheme disadvantages the tree-sitter example, true, but also things like lack of differentiating highlighting on underscores or dollar signs jump out. Also, the regex-based highlighter does neat things like color the nested `\begin` and `\end` tokens differently to match them with their counterpart, which should be tree-sitter's bread & butter.

**Comment by pfoerster** [comment]
> Unfortunately the highlighting this grammar provides does not compare favorably with neovim's built-in regex-based latex highlighter.

Yeah, I can imagine that one. Originally, this grammar was designed to replace the parser of `texlab` (but in the end it did not end up replacing it). So there still needs some work to be done in order to provide a good highlighting experience. I was hoping that this grammar can provide a good foundation for a tree-sitter based highlighter. 

> My chosen colorscheme disadvantages the tree-sitter example, true, but also things like lack of differentiating highlighting on underscores or dollar signs jump out.

This is not something, I can easily fix in my repository as I only provide the actual parser and not the highlighting queries. These live in another repository. I think its `nvim-treesitter`. The only change I can make from my side is parsing sub- and superscripts correctly.

> Also, the regex-based highlighter does neat things like color the nested \begin and \end tokens differently to match them with their counterpart, which should be tree-sitter's bread & butter.

I am assuming you mean some kind of rainbow highlighting? In that case, I would say that it is quite difficult with tree-sitter's highlighting engine but I am not sure. Again, you may be better off reporting this over at `nvim-treesitter` as I am not in charge of the highlighting queries. I only provide the grammar itself and nothing else.

**Comment by ahelwer** [comment]
@pfoerster Thanks for all your work on this grammar! I too wrote my own tree-sitter grammar with the hope it would serve as the backbone of an interpreter for that language; I discovered (as I assume you did) tree-sitter isn't really designed for that use-case.

This actually kinda dovetails with an issue of my expectations about where the highlighting rules should live (see https://github.com/nvim-treesitter/nvim-treesitter/issues/1478); the [tree-sitter syntax highlighting docs](https://tree-sitter.github.io/tree-sitter/syntax-highlighting#query-paths) say it should live with the grammar in the repo, but I guess nvim-treesitter separates those queries into nvim itself? Seems strange; the nature of those queries is they are separated from any particular colorscheme, are tightly bound to the design of the grammar itself, and are standard enough to be independent from any client of the tree-sitter grammar. So, it would make sense for them to live in the grammar repo with the grammar itself. But perhaps I'm not seeing the big picture here. Anyway, feel free to close this as I guess those queries are separate from this grammar.

**Comment by clason** [comment]
The highlighting queries _for neovim_ indeed live in https://github.com/nvim-treesitter/nvim-treesitter/tree/master/queries/latex (it turns out that while much of it can be shared, some details are specific to the actual use case -- i.e., _how_ the queries are used). But I, too, often struggle with whether a certain feature is something that can be done by a query or should be implemented in the parser... I'm sure help with extending is appreciated on both sides!

For what it's worth, the current queries are already pretty close to feature-parity with the _base_ `tex.vim` syntax file,  but the extended, package-aware rules (especially those in the `vimtex` filetype plugin) are on a different level, still (and I'm not sure how reasonable it is to expect a similar support from the "built-in" tree-sitter highlighting; I think this requires a separate `nvimtex` plugin).

Color schemes are indeed a separate thing; `nvim-treesitter` defines basic `TSFunction` etc. highlight groups, but they _also_ define more low-level `texTSFoo` groups for the actual captures, so you can use them for a LaTeX-specific color scheme.
